# Generated by Django 3.0.8 on 2020-08-04 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Rental',
            fields=[
                ('ref', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Returned'), (2, 'Not Returned')], default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
