name: 'Terraform GitHub Actions'
on:
  - pull_request
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: vitr/actions-build-and-upload-to-ecs@master
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: loribooks
          region: us-east-1
          tags: latest,${{ github.sha }}
          create_repo: true
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Terraform Init
        uses: Yellow-Box-Software/terraform-action@v2.5
        with:
          args: "init terraform"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Validate
        uses: Yellow-Box-Software/terraform-action@v2.5
        with:
          args: "validate --var-file=terraform/testing.tfvars terraform"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Plan
        uses: Yellow-Box-Software/terraform-action@v2.5
        with:
          args: "plan --var-file=terraform/testing.tfvars terraform"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Terraform Apply
        uses: Yellow-Box-Software/terraform-action@v2.5
        with:
          args: "apply --var-file=testing.tfvars terraform"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
